### ISSUE TITLE
Pipeline fails in the LINT stage for v41

### ISSUE THREAD

**Issue by srinikitha09** [SAP/cloud-s4-sdk-pipeline#48] opened 2020-08-27 08:08 UTC
## Issue Description (Mandatory)

The pipeline is failing in the stage: LINT

The pipeline fails while running with v41 during the Lint stage. It fails in checkUi5BestPractices step. Currently, we are using warnings-ng plugin of version 8.3.0. May be do we need to use the latest version of that plugin?

## Log Output (Mandatory)

```
09:53:22  [2020-08-27T07:53:22.003Z] ----------------------------------------------------------
09:53:22  [2020-08-27T07:53:22.003Z]     ERROR OCCURRED IN LIBRARY STEP: checkUi5BestPractices
09:53:22  [2020-08-27T07:53:22.003Z] ----------------------------------------------------------
09:53:22  [2020-08-27T07:53:22.003Z] 
09:53:22  [2020-08-27T07:53:22.003Z] Error Details:
09:53:22  [2020-08-27T07:53:22.003Z] **********************************************************
09:53:22  [2020-08-27T07:53:22.003Z]     java.lang.IllegalArgumentException: WARNING: Unknown parameter(s) found for class type 'io.jenkins.plugins.analysis.core.steps.RecordIssuesStep': skipPublishingChecks
09:53:22  [2020-08-27T07:53:22.003Z] **********************************************************
09:53:22  [2020-08-27T07:53:22.003Z] 
09:53:22  [Pipeline] echo
09:53:22  [2020-08-27T07:53:22.011Z] Parameters available to this step are: [script:WorkflowScript@3969121d, configuration:[ui5BestPractices:[failThreshold:[error:100, warning:500, info:1000]]], ui5Components:[app/webapp/Component.js]]
```

## Link to Jenkins Job (if it can be shared)

PLEASE PLACE THE LINK HERE

## Reproduce the Issue Locally (Mandatory)

In case a maven/npm command or similar failed:
* [ ] I tried to reproduce the issue locally
* [ ] I could reproduce the issue locally

## Search for existing solution beforehand (Mandatory)

* [ ] I searched for an existing solution on [StackOverflow](https://stackoverflow.com/questions/tagged/sap-cloud-sdk) and my question was not answered there
* [ ] I searched for a similar GitHub issue before and found none
* [ ] I checked the [pipeline configuration docs](https://github.com/SAP/cloud-s4-sdk-pipeline/blob/master/configuration.md) and [the general pipeline docs](https://github.com/SAP/cloud-s4-sdk-pipeline/tree/master/doc/pipeline) for an answer of my issue

***Please try the GitHub search, it works really well***

## Project Details (Mandatory)

* Link to GitHub repo: PLACE YOUR LINK HERE
* Project type, for example:
    * [ ] SDK Maven Archetype
    * [ ] MTA (which types of modules?)
    * [ ] JavaScript
    * [ ] None of the above (unsupported)

**Comment by stippi2** [comment] 2020-08-27 09:38
**Short version:** Can you update the version of the Warnings NG plugin to 8.4.1? The property will exist then and your pipeline should not fail anymore. Please let us know your findings.

**Long version:** There was a regression introduced in the Warnings NG plugin with [this commit](https://github.com/jenkinsci/warnings-ng-plugin/pull/550). It activates a feature by default, which requires the Jenkins "Root-URL" to be configured. This URL is normally configured, but not in all use-cases of the CX Server. My work-around was to set the new parameter "skipPublishingChecks" for the `recordIssues` step in order to de-activate the new feature. This however, would not have solved the issue for anyone consuming the Cloud SDK Pipeline in a version that does not contain that fix. And so we also fixed the version of the Warnings NG plugin to 8.3.0 in the CX Server scripts. This means we should see the same failure as you in our internal tests, since we also run with version 8.3.0 of the plugin. But for some reason, it is just a warning in our logs and no pipeline failure. So we were unaware that passing the property to recordIssues is actually wrong and should have been removed again.

**Comment by stippi2** [comment] 2020-08-28 09:24
I have created a backlog issue to solve this problem. I assume we can simply pass the property depending on the plugin-version and we will fix this soon.

Can I close this ticket, because upgrading the plugin worked and the issue is solved for you?

**Comment by srinikitha09** [comment] 2020-08-31 05:54
Thanks for the clarity. We did not upgrade the plugin yet. Of course, you can close the ticket. We have another backlog item, which enables the usage of specific jenkinsfilerunner image for each kind of job. Once, this is achieved, we would not have problem with the versions update of plugins.

Because, currently, we are afraid if upgrading the warnings-ng plugin to 8.4.1 still supports the older version of cloud sdk pipeline ex: v39 which worked with warnings-ng 8.3.0 version.

**Comment by KevinHudemann** [comment] 2020-11-27 15:03
Hi @srinikitha09,
the issue in the SAP Cloud SDK Pipeline has been resolved by @stippi2 in version v42, thus closing this issue.

Due to the deprecation of the SAP Cloud SDK Pipeline, however, we recommend the switch to the [General Purpose Pipeline of project "Piper"](https://sap.github.io/jenkins-library/stages/introduction/) where the issue you reported is **not** resolved yet. If you want to stay informed about the progress there, please feel free to open an [issue in the repository of the General Purpose Pipeline of project "Piper"](https://github.com/SAP/jenkins-library/issues/new).
Best Regards,
Kevin

**Closed by KevinHudemann** 2020-11-27 15:03 UTC
